name: Build-arm64

on:
  schedule:
    - cron: '0 21 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup node
        uses: actions/setup-node@v2
        with:
         node-version: '14'
      
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y libarchive-tools

      - name: Build
        run: |
          rm -rf ./blockbench*/
          export version=$(curl -s https://api.github.com/repos/JannisX11/blockbench/releases/latest | grep -oP '"tag_name": "\K(.*)(?=")' | tr -d 'v')
          git clone https://github.com/JannisX11/blockbench.git
          cd blockbench && npm install 
          sed -i "s+icon:'icon.ico'+icon:'/opt/Blockbench/icon.png'+g" ./main.js #for taskbar icon
          npx electron-builder --linux zip --arm64 --publish never
          wget https://github.com/JannisX11/blockbench/releases/download/v4.0.5/Blockbench_4.0.5.deb -O ../sample.deb
          dpkg-deb -R ../sample.deb ../blockbench-deb
          rm -f ../sample.deb
          cp dist/Blockbench*.zip ../blockbench-deb/opt
          rm -rf ../blockbench-deb/opt/Blockbench
          cd ../blockbench-deb/opt
          unzip ./*zip -d Blockbench
          rm *zip
          cp ../../blockbench/icon.png ./Blockbench
          rm -rf ../usr/share/icons
          sed -i s+Icon=blockbench+Icon=/opt/Blockbench/icon.png+g ../usr/share/applications/*
          sed -i s+Categories=3DGraphics+Categories=Development+g ../usr/share/applications/*
          sed -i 's/amd64/arm64/g' ../DEBIAN/control
          cd ../..
          dpkg-deb -b ./blockbench-deb blockbench_"$version"_arm64.deb

      - name: Upload
        run: |
          rm -rf ./blockbench*/
          git config user.name 'GitHub Actions'
          git config user.email 'github-actions@github.com'
          git add .
          git commit -m "upload blockbench v$(curl -s https://api.github.com/repos/JannisX11/blockbench/releases/latest | grep -oP '"tag_name": "\K(.*)(?=")' | tr -d 'v')"
          git push origin master
